version: '2'

services:
  redis:
      image: redis
      ports:
         - "6379:6379"
  mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: uic